"""
generate_content_version_csv.py

Two-step workflow:

  STEP 1 — Generate the email ID map template from your output folder:
      python generate_content_version_csv.py --generate-map

      Scans output/ for subfolders, writes email_id_map.csv with each
      subfolder name pre-populated as external_id. Fill in email_message_id
      manually, then proceed to step 2.

  STEP 2 — Generate the ContentVersion upload CSV:
      python generate_content_version_csv.py

      Reads email_id_map.csv and output/, base64-encodes every file, and
      writes content_version_upload.csv ready for Salesforce Data Loader.
      Rows with a blank email_message_id are skipped with a warning.

Expected folder structure:
    output/
      <external_id>/
        attachment1.pdf
        attachment2.xlsx
      <external_id>/
        photo.png

email_id_map.csv format (generated by --generate-map, you fill in column 2):
    external_id,email_message_id
    550e8400-e29b-41d4-a716-446655440000,02s8X000001abcDEF
    6ba7b810-9dad-11d1-80b4-00c04fd430c8,
"""

import argparse
import base64
import csv
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------

DEFAULT_OUTPUT_DIR = Path("output")
DEFAULT_MAP_CSV    = Path("email_id_map.csv")
DEFAULT_OUT_CSV    = Path("content_version_upload.csv")

CV_FIELDS = [
    "Title",                   # filename without extension
    "PathOnClient",            # full filename with extension
    "VersionData",             # base64-encoded file contents
    "ContentLocation",         # always "S" (Salesforce-hosted)
    "FirstPublishLocationId",  # SF EmailMessage Id — auto-creates ContentDocumentLink
    "Description",             # relative path for traceability, e.g. uuid/invoice.pdf
]


# ---------------------------------------------------------------------------
# Step 1 — Generate map template
# ---------------------------------------------------------------------------

def generate_map(output_dir: Path, map_csv: Path) -> None:
    """
    Scan output_dir for immediate subfolders and write a map CSV template
    with external_id populated and email_message_id left blank for manual entry.
    """
    if not output_dir.exists():
        print(f"[ERROR] Output folder not found: {output_dir.resolve()}")
        sys.exit(1)

    subfolders = sorted(
        p.name for p in output_dir.iterdir() if p.is_dir()
    )

    if not subfolders:
        print(f"[ERROR] No subfolders found in {output_dir.resolve()}")
        sys.exit(1)

    with open(map_csv, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["external_id", "email_message_id"])
        writer.writeheader()
        for name in subfolders:
            writer.writerow({"external_id": name, "email_message_id": ""})

    print(f"\nGenerated map template → {map_csv.resolve()}")
    print(f"  {len(subfolders)} subfolder(s) written as external_id.")
    print(f"\nNext: fill in the email_message_id column, then run:")
    print(f"  python {Path(__file__).name}\n")


# ---------------------------------------------------------------------------
# Step 2 — Generate upload CSV
# ---------------------------------------------------------------------------

def load_map(map_csv: Path) -> dict[str, str]:
    """
    Load external_id → email_message_id from the map CSV.
    Rows with a blank email_message_id are included with an empty string
    so we can warn per-folder rather than silently drop them.
    """
    if not map_csv.exists():
        print(
            f"[ERROR] Map file not found: {map_csv.resolve()}\n"
            f"        Run with --generate-map first to create it."
        )
        sys.exit(1)

    mapping: dict[str, str] = {}
    with open(map_csv, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        required = {"external_id", "email_message_id"}
        if not required.issubset(reader.fieldnames or []):
            print(
                f"[ERROR] '{map_csv}' must have columns: {', '.join(required)}\n"
                f"        Found: {reader.fieldnames}"
            )
            sys.exit(1)
        for row in reader:
            ext_id = row["external_id"].strip()
            sf_id  = row["email_message_id"].strip()
            if ext_id:
                mapping[ext_id] = sf_id  # sf_id may be blank — handled in scan

    print(f"  Loaded {len(mapping)} row(s) from {map_csv}")
    return mapping


def encode_file(path: Path) -> str:
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")


def scan_and_build_rows(
    output_dir: Path,
    email_id_map: dict[str, str],
) -> tuple[list[dict], list[str]]:
    """
    Walk output_dir and build one ContentVersion row per file.

    Returns:
        rows     — dicts ready to write to CSV
        warnings — human-readable messages for every skipped file
    """
    rows: list[dict] = []
    warnings: list[str] = []

    all_files = sorted(f for f in output_dir.rglob("*") if f.is_file())

    if not all_files:
        print(f"[WARN] No files found under {output_dir.resolve()}")
        return rows, warnings

    for file_path in all_files:
        relative    = file_path.relative_to(output_dir)
        external_id = relative.parts[0] if len(relative.parts) > 1 else None

        if external_id is None:
            warnings.append(f"SKIP (root-level file, no folder key): {file_path.name}")
            continue

        if external_id not in email_id_map:
            warnings.append(f"SKIP (folder not in map): {relative}")
            continue

        sf_id = email_id_map[external_id]
        if not sf_id:
            warnings.append(
                f"SKIP (email_message_id blank for '{external_id}'): {relative}"
            )
            continue

        rows.append({
            "Title":                  file_path.stem,
            "PathOnClient":           file_path.name,
            "VersionData":            encode_file(file_path),
            "ContentLocation":        "S",
            "FirstPublishLocationId": sf_id,
            "Description":            str(relative),
        })

    return rows, warnings


def write_csv(rows: list[dict], out_path: Path) -> None:
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CV_FIELDS)
        writer.writeheader()
        writer.writerows(rows)
    print(f"  Wrote {len(rows)} row(s) → {out_path.resolve()}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a ContentVersion CSV for Salesforce Data Loader.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Steps:
  1. python generate_content_version_csv.py --generate-map
       Scans output/ and writes email_id_map.csv with external_id pre-filled.
       Open email_id_map.csv and fill in the email_message_id column.

  2. python generate_content_version_csv.py
       Reads email_id_map.csv and output/, and writes content_version_upload.csv.
        """,
    )
    parser.add_argument(
        "--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR,
        help=f"Folder to scan for attachments (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--map", type=Path, default=DEFAULT_MAP_CSV,
        help=f"Map CSV path (default: {DEFAULT_MAP_CSV})",
    )
    parser.add_argument(
        "--out", type=Path, default=DEFAULT_OUT_CSV,
        help=f"Output CSV path (default: {DEFAULT_OUT_CSV})",
    )
    parser.add_argument(
        "--generate-map", action="store_true",
        help="Scan output folder and generate the email_id_map.csv template (step 1)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if args.generate_map:
        generate_map(args.output_dir, args.map)
        return

    # Step 2 — build upload CSV
    if not args.output_dir.exists():
        print(f"[ERROR] Output folder not found: {args.output_dir.resolve()}")
        sys.exit(1)

    print(f"\nScanning   : {args.output_dir.resolve()}")
    print(f"Map CSV    : {args.map.resolve()}")
    print(f"Output CSV : {args.out.resolve()}\n")

    email_id_map        = load_map(args.map)
    rows, warnings      = scan_and_build_rows(args.output_dir, email_id_map)

    if warnings:
        print(f"── Warnings ({len(warnings)}) ──")
        for w in warnings:
            print(f"  {w}")
        print()

    if not rows:
        print("[ERROR] No rows to write. Check your folder structure and map CSV.")
        sys.exit(1)

    print("── Writing CSV ──")
    write_csv(rows, args.out)

    print(f"""
┌─────────────────────────────────┐
│            Summary              │
├──────────────────┬──────────────┤
│  Files included  │ {len(rows):>12} │
│  Files skipped   │ {len(warnings):>12} │
└──────────────────┴──────────────┘
""")


if __name__ == "__main__":
    main()